[[jason-kumpf]]
Jason Kumpf
-----------

*Laurel, MD | kumpf.jason@gmail.com*

[[experience]]
Experience
~~~~~~~~~~

[[software-engineer]]
Software Engineer
^^^^^^^^^^^^^^^^^

_https://senseye.io[Senseye] - November 2017 - December 2018_

Worked with both customers and other developers to develop various tools
and additions to the data ingestion pipeline, which fed the main
product. Worked heavily on and with micro-services and AWS in a
fast-paced, scrum driven, fully remote and very agile development team.
Being remote for 90% of the team, communication and documentation was
vital. During a transition of project management, my team began the
switch to TypeScript and more sophisticated AWS/ECS integration for both
testing and continuous integration.

[[adjunct-faculty]]
Adjunct Faculty
^^^^^^^^^^^^^^^

_http://www.uc.edu[University of Cincinnati] - August 2015 - June 2016_

Full time adjunct faculty member (in the College of Education, Criminal
Justice and Human Services IT Department) responsible for teaching
courses on contemporary programming in C# and front-end web development.
Other courses were network design and database design with SQL Server.
Also responsible for advising senior capstone projects for 35 seniors
through the course of their projects development.

[[senior-software-engineer]]
Senior Software Engineer
^^^^^^^^^^^^^^^^^^^^^^^^

_https://www.linkedin.com/company/academic-benchmarks/about/[Academic
Benchmarks] - March 2013 - November 2014_

Participated in all phases of the software development life-cycle,
including the architecture of solutions, creation of design
documentation, coding and developing test plans. Provided multiple
aspects to solve problems and coordinate team discussions to decide on
the best solution not only for the given problem but, for potential
larger issues. Helped to provide leadership to the team and mentor more
junior developers. Brought a creative perspective to projects and/or
solutions to problems so as to broaden the scope and determine other
potential impacts throughout the product line and/or customers.
Constantly stayed current on the latest technologies and best practices
in web and software development and always looking for ways to improve
the quality of the team and our development process.

[[research-assistant---webdbsysadmin]]
Research Assistant - Web/DB/SysAdmin
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

_http://ucii.ceas.uc.edu/[University of Cincinnati Infrastructure
Institute] - September 2008 - August 2014_

Responsible for upgrading and converting the research group's web
application for reporting the real time status of various bridge
monitors or monitoring of sensor data projects which included a real
time assessment of the general public's physical safety from potential
harm due to certain weather conditions. (see Paper below). The systems
grew as several new projects were taken on at the beginning and through
the time spent there. Most projects involved pretty complex decision
making and time critical scheduling often times over unreliable
connections and several weather damaging events. Lead the group into
rebuilding the whole system into a more robust and standardized solution
from code down to methods for implementing new systems and new features.

[[interim-it-director]]
Interim IT Director
^^^^^^^^^^^^^^^^^^^

_http://www.uc.edu[University of Cincinnati] - June 2004 - August 2008_

Started as Applications analyst developing and improving software
developed for various custom aspects of the IT infrastructure and
operations. Took over system administrative responsibilities of former
employee managing IT infrastructure affecting 200+ employees and 5000+
students data and access to those IT resources. Became the Interim IT
Director upon request of supervisor to perform the duties of another
former employee responsible for managing the IT staff, support
operations and computer classroom equipment. Managed $500,000 annual
budget to support the 600+ computer systems, data center and staff
salaries.

[[applications-analyst]]
Applications Analyst
^^^^^^^^^^^^^^^^^^^^

_http://www.uc.edu[University of Cincinnati]- June 2004 - August 2008_

Responsible for maintaining and supporting IT operations affected by
both Victory Parkway and Clifton campus data centers and equipment.
Operations affected include login of all CAS computer labs, faculty and
staff office computer login and shared file access. Will provide
constant monitoring of server and network performance to provide fault
tolerance for critical applications and reduce redundancy of
services/applications. Additional duties include the development of
support materials (CMS or Technical knowledge, manuals, etc.),
conducting occasional training sessions, moderate supervision of team
members' projects and student workers.

[[programmeranalyst]]
Programmer/Analyst
^^^^^^^^^^^^^^^^^^

_https://www.safeschools.com/[Scenario Learning/Safe Schools] - 10/2002
- 1/2004, Cincinnati, OH_

In charge of developing a web application involving extensive Perl, XML,
XSL, Apache, MySQL, and ActionScript knowledge. Current projects include
developing an in-house SGML/XML document management system to be used to
synchronize on-line documents with in-house documents. Came up with an
easy solution to convert MS Word documents to SML/XML DocBook markup.

[[programmeranalyst-1]]
Programmer/Analyst
^^^^^^^^^^^^^^^^^^

_https://www.knovationlearning.com/[Thinkronize/Knovation] - 6/2000 -
10/2002, Cincinnati, OH_

Determine system requirements by working with programming manager,
product managers, and others as needed. Provide technical perspective to
high-level design discussions. Develop system designs that effectively
meet user requirements, efficiently operate, and effectively integrate
with other systems. Develop and write software that operates efficiently
and provides flexibility for future revisions. Fully test software and
place into production. Resolve issues related to production software.
Provide support for staff PCs and SunRay Workstations, including
internal networking. Aid in development and support of internal software
used daily by most of the staff which served the primary library or
knowledge base for the company's product line and services.

[[education]]
Education
~~~~~~~~~

[[b.s.-information-engineering-technology]]
B.S. Information Engineering Technology
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

_University of Cincinnati - September 1997 - June 2001_

* *Senior Design Project*: Web-Based Virtual Laboratory (Content
Management System)

[[b.s.-mechanical-engineering-technology]]
B.S. Mechanical Engineering Technology
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

_University of Cincinnati - September 1994 - June 2001_

* *Senior Project*: Automated Data Collection System for Heat Transfer
Laboratory Experiment

[[ph.d.-abd-electrical-engineering]]
Ph.D. (ABD) Electrical Engineering
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

_University of Cincinnati - September 2008 - May 2015_

* *Relevant Coursework*: Intelligent Systems, Multi-variable Control,
Stochastic Models.
* *Extra*: Completed the Preparing Future Faculty Training
* *Research Topic*: Calibration of Finite Element Models for Online
Bridge Health Monitoring Systems

[[publications]]
Publications
~~~~~~~~~~~~

https://www.researchgate.net/publication/257921037_Automated_Ice_Inference_and_Monitoring_on_the_Veterans_Glass_City_Skyway_Bridge[Kumpf,
J., Helmicki, A., Nims, D., Hunt, V., and Agrawal, S. (2012). "Automated
Ice Inference and Monitoring on the Veterans' Glass City Skyway Bridge."
J. Bridge Eng. 17, SPECIAL ISSUE: Nondestructive Evaluation and Testing
for Bridge Inspection and Evaluation, 975-978.]

[[references]]
References
~~~~~~~~~~

Available Upon Request
